# Generated by Django 2.0.2 on 2018-05-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databasePractice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='addrese',
            field=models.CharField(default='xian', max_length=64),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(default='root@163.com', max_length=64),
        ),
    ]
